std = "roblox"
exclude = ["src/Server/Tests/**"]

[config]
globals = ["describe", "it", "expect"]

[rules]
shadowing = "allow"
roblox_incorrect_roblox_api = "allow"
incorrect_standard_library_use = "allow"
multiple_statements = "allow"
roblox_manual_fromscale_or_fromoffset = "allow"
global_usage = "warn"
undefined_variable = "warn"
unused_variable = "allow"
