std = "roblox"

[config]
globals = ["describe", "it", "expect"]

[rules]
shadowing = "allow"
roblox_incorrect_roblox_api = "allow"
multiple_statements = "allow"
global_usage = "allow"
undefined_variable = "allow"
unused_variable = "allow"
