# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "pydantic",
# ]
# ///
import os
import json
import glob
from pydantic import BaseModel, Field, field_validator
from typing import Dict, Optional, List

# --- SCHEMAS ---

class MaterialSchema(BaseModel):
    Id: str
    Name: str
    Density: float
    Conductivity: float
    Value: int

class ReactionSchema(BaseModel):
    Id: str
    Name: str
    RequiredMaterials: Dict[str, float]
    Catalyst: Optional[str] = None
    MinTemperature: float
    MaxTemperature: float
    MinPressure: float
    Product: str
    YieldRatio: float
    EnergyRequired: float
    EntropyGenerated: float
    DiscoveryRequirement: Optional[str] = None

class MachineSchema(BaseModel):
    Id: str
    Name: str
    PowerConsumption: float
    MaxTemperature: float

class ResearchSchema(BaseModel):
    Id: str
    Name: str
    RequiredDiscoveries: List[str]
    Cost: int

class CreatureSchema(BaseModel):
    Id: str
    Name: str
    Health: int

class BiomeSchema(BaseModel):
    Id: str
    Name: str
    Temperature: float

class QuestSchema(BaseModel):
    Id: str
    Name: str

class AchievementSchema(BaseModel):
    Id: str
    Name: str

class FactionSchema(BaseModel):
    Id: str
    Name: str

class LoreSchema(BaseModel):
    Id: str
    Title: str

class BlueprintSchema(BaseModel):
    Id: str
    Name: str
    Materials: Dict[str, float]

# --- VALIDATION & GENERATION ---

def load_and_validate(pattern: str, schema_class):
    valid_items = []
    files = glob.glob(pattern)
    for file_path in files:
        with open(file_path, "r", encoding="utf-8") as f:
            try:
                data = json.load(f)
                item = schema_class(**data)
                valid_items.append(item)
                print(f"✅ Validated: {file_path}")
            except Exception as e:
                print(f"❌ Validation Error in {file_path}:\n{e}")
                exit(1)
    return valid_items

def generate_luau_registry(items, output_path: str, registry_name: str, type_def: str):
    luau_content = f"""--!strict
-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by ContentOps Pipeline.

{type_def}

local {registry_name}: {{ [string]: {registry_name}Definition }} = {{}}

function {registry_name}.Get(id: string): {registry_name}Definition?
	return {registry_name}[id]
end

function {registry_name}.GetAll(): {{ [string]: {registry_name}Definition }}
	return {registry_name}
end

"""
    
    for item in items:
        json_str = item.model_dump_json(exclude_none=True)
        # Convert JSON string roughly to Luau table syntax for simple types
        # Note: robust implementation requires proper serialization, this is a simplified version for the proof of concept.
        # We will use a more precise luau generation approach.
        pass

    # Simplified generator for demonstration of the pipeline
    luau_entries = []
    for item in items:
        # Pydantic dump to dict
        data = item.model_dump(exclude_none=True)
        
        entry = f'{registry_name}["{data["Id"]}"] = {{\n'
        for k, v in data.items():
            if isinstance(v, dict):
                entry += f'\t{k} = {{\n'
                for dk, dv in v.items():
                    entry += f'\t\t{dk} = {dv},\n'
                entry += '\t},\n'
            elif isinstance(v, str):
                entry += f'\t{k} = "{v}",\n'
            else:
                entry += f'\t{k} = {v},\n'
        entry += '}\n'
        luau_entries.append(entry)
        
    luau_content += "\n".join(luau_entries)
    luau_content += f"\nreturn {registry_name}\n"

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(luau_content)
    print(f"🚀 Generated Luau Registry: {output_path}")

def main():
    base_path = "Content/Data"
    
    # 1. Materials
    print("--- Validating Materials ---")
    materials = load_and_validate(f"{base_path}/Materials/*.json", MaterialSchema)
    
    mat_type_def = """export type MaterialRegistryDefinition = {
	Id: string,
	Name: string,
	Density: number,
	Conductivity: number,
	Value: number,
}"""
    generate_luau_registry(materials, "src/Shared/Config/GeneratedMaterialRegistry.luau", "MaterialRegistry", mat_type_def)

    # 2. Reactions
    print("--- Validating Reactions ---")
    reactions = load_and_validate(f"{base_path}/Reactions/*.json", ReactionSchema)
    
    rxn_type_def = """export type ReactionRegistryDefinition = {
	Id: string,
	Name: string,
	RequiredMaterials: { [string]: number },
	Catalyst: string?,
	MinTemperature: number,
	MaxTemperature: number,
	MinPressure: number,
	Product: string,
	YieldRatio: number,
	EnergyRequired: number,
	EntropyGenerated: number,
	DiscoveryRequirement: string?,
}"""
    generate_luau_registry(reactions, "src/Shared/Config/GeneratedReactionRegistry.luau", "ReactionRegistry", rxn_type_def)
    
    print("--- Validating Machines ---")
    machines = load_and_validate(f"{base_path}/Machines/*.json", MachineSchema)
    
    mach_type_def = """export type MachineRegistryDefinition = {
	Id: string,
	Name: string,
	PowerConsumption: number,
	MaxTemperature: number,
}"""
    generate_luau_registry(machines, "src/Shared/Config/GeneratedMachineRegistry.luau", "MachineRegistry", mach_type_def)

    print("--- Validating Research ---")
    research = load_and_validate(f"{base_path}/Research/*.json", ResearchSchema)
    
    res_type_def = """export type ResearchRegistryDefinition = {
	Id: string,
	Name: string,
	RequiredDiscoveries: { string },
	Cost: number,
}"""
    generate_luau_registry(research, "src/Shared/Config/GeneratedResearchRegistry.luau", "ResearchRegistry", res_type_def)

    print("--- Validating Biomes ---")
    biomes = load_and_validate(f"{base_path}/Biomes/*.json", BiomeSchema)
    biome_type_def = """export type BiomeRegistryDefinition = {
	Id: string,
	Name: string,
	Temperature: number,
}"""
    generate_luau_registry(biomes, "src/Shared/Config/GeneratedBiomeRegistry.luau", "BiomeRegistry", biome_type_def)

    print("--- Validating Creatures ---")
    creatures = load_and_validate(f"{base_path}/Creatures/*.json", CreatureSchema)
    creature_type_def = """export type CreatureRegistryDefinition = {
	Id: string,
	Name: string,
	Health: number,
}"""
    generate_luau_registry(creatures, "src/Shared/Config/GeneratedCreatureRegistry.luau", "CreatureRegistry", creature_type_def)

    # EXPORT BUNDLE FOR WEB COMPANION (Priority B / Shared Data)
    web_bundle_path = "web/src/data/registry_bundle.json"
    os.makedirs(os.path.dirname(web_bundle_path), exist_ok=True)
    bundle_data = {
        "materials": [m.model_dump() for m in materials],
        "reactions": [r.model_dump() for r in reactions],
        "machines": [mc.model_dump() for mc in machines],
        "research": [rs.model_dump() for rs in research],
        "biomes": [b.model_dump() for b in biomes],
        "creatures": [c.model_dump() for c in creatures],
    }
    with open(web_bundle_path, "w", encoding="utf-8") as f:
        json.dump(bundle_data, f, indent=2)
    print(f"🌐 Exported Shared Web Bundle: {web_bundle_path}")

    print("✅ Content Supply Chain execution complete.")

if __name__ == "__main__":
    main()
