# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "pydantic",
# ]
# ///
import os
import json
import glob
import hashlib
import datetime
import subprocess
from pydantic import BaseModel, Field
from typing import Dict, Optional, List, Any

# --- SCHEMAS ---

class MaterialSchema(BaseModel):
    Id: str
    Name: str
    Density: float
    Conductivity: float
    Value: int

class ReactionSchema(BaseModel):
    Id: str
    Name: str
    RequiredMaterials: Dict[str, float]
    Catalyst: Optional[str] = None
    MinTemperature: float
    MaxTemperature: float
    MinPressure: float
    Product: str
    YieldRatio: float
    EnergyRequired: float
    EntropyGenerated: float
    DiscoveryRequirement: Optional[str] = None

class MachineSchema(BaseModel):
    Id: str
    Name: str
    PowerConsumption: float
    MaxTemperature: float

class ResearchSchema(BaseModel):
    Id: str
    Name: str
    RequiredDiscoveries: List[str]
    Cost: int

class BiomeSchema(BaseModel):
    Id: str
    Name: str
    Temperature: float

class CreatureSchema(BaseModel):
    Id: str
    Name: str
    Health: int

class SpiritSchema(BaseModel):
    Id: str
    Name: str
    Description: str
    Rarity: str
    Element: str
    DropRate: str

class BadgeSchema(BaseModel):
    Id: str
    Name: str
    Description: str
    RarityPercent: float

class RecipeSchema(BaseModel):
    Id: str
    Name: str
    Description: str
    Ingredients: List[str]
    OutputType: str

class MarketAssetSchema(BaseModel):
    Id: str
    Name: str
    Description: str
    Price: int
    Currency: str
    Category: str
    ImageUrl: str

# --- UTILS ---

def get_git_commit():
    try:
        return subprocess.check_output(['git', 'rev-parse', 'HEAD']).decode('ascii').strip()
    except Exception:
        return "unknown"

def compute_hash(data: str) -> str:
    return hashlib.sha256(data.encode('utf-8')).hexdigest()

# --- VALIDATION & GENERATION ---

def load_and_validate(pattern: str, schema_class):
    valid_items = []
    files = glob.glob(pattern)
    for file_path in files:
        with open(file_path, "r", encoding="utf-8") as f:
            try:
                data = json.load(f)
                item = schema_class(**data)
                valid_items.append(item)
                print(f"✅ Validated: {file_path}")
            except Exception as e:
                print(f"❌ Validation Error in {file_path}:\n{e}")
                exit(1)
    return valid_items

def generate_luau_registry(items, output_path: str, registry_name: str, type_def: str):
    # Generate backward-compatible alias functions
    singular_name = registry_name.replace("Registry", "")
    # For Luau registries, plural form matches the registry name without "Registry"
    # e.g., MaterialRegistry -> GetMaterial, GetAllMaterials
    # ResearchRegistry -> GetResearch, GetAllResearch (same singular/plural)
    plural_name = singular_name
    
    luau_content = f"""--!strict
-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by ContentOps Pipeline.

{type_def}

local {registry_name}: {{ [string]: {registry_name}Definition }} = {{}}

function {registry_name}.Get(id: string): {registry_name}Definition?
	return {registry_name}[id]
end

function {registry_name}.GetAll(): {{ [string]: {registry_name}Definition }}
	return {registry_name}
end

-- Backward-compatible aliases (legacy API)
function {registry_name}.Get{singular_name}(id: string): {registry_name}Definition?
	return {registry_name}[id]
end

function {registry_name}.GetAll{plural_name}(): {{ [string]: {registry_name}Definition }}
	return {registry_name}
end

"""
    luau_entries = []
    items = sorted(items, key=lambda x: x.Id)
    for item in items:
        data = item.model_dump(exclude_none=True)
        entry = f'{registry_name}["{data["Id"]}"] = {{\n'
        for k, v in data.items():
            if isinstance(v, dict):
                entry += f'\t{k} = {{\n'
                for dk, dv in v.items():
                    entry += f'\t\t{dk} = {dv},\n'
                entry += '\t},\n'
            elif isinstance(v, list):
                array_str = ", ".join([f'"{x}"' if isinstance(x, str) else str(x) for x in v])
                entry += f'\t{k} = {{{array_str}}},\n'
            elif isinstance(v, str):
                # Escape quotes
                safe_str = v.replace('"', '\\"')
                entry += f'\t{k} = "{safe_str}",\n'
            else:
                entry += f'\t{k} = {v},\n'
        entry += '}\n'
        luau_entries.append(entry)
        
    luau_content += "\n".join(luau_entries)
    luau_content += f"\nreturn {registry_name}\n"

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(luau_content)
    print(f"🚀 Generated Luau Registry: {output_path}")

def export_json(data: Any, path: str):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)

def main():
    base_path = "Content/Data"
    registry_dir = "web/src/data/registry"
    
    print("--- Validating Content ---")
    
    materials = load_and_validate(f"{base_path}/Materials/*.json", MaterialSchema)
    reactions = load_and_validate(f"{base_path}/Reactions/*.json", ReactionSchema)
    machines = load_and_validate(f"{base_path}/Machines/*.json", MachineSchema)
    research = load_and_validate(f"{base_path}/Research/*.json", ResearchSchema)
    biomes = load_and_validate(f"{base_path}/Biomes/*.json", BiomeSchema)
    creatures = load_and_validate(f"{base_path}/Creatures/*.json", CreatureSchema)
    spirits = load_and_validate(f"{base_path}/Spirits/*.json", SpiritSchema)
    badges = load_and_validate(f"{base_path}/Badges/*.json", BadgeSchema)
    recipes = load_and_validate(f"{base_path}/Recipes/*.json", RecipeSchema)
    market = load_and_validate(f"{base_path}/Market/*.json", MarketAssetSchema)
    
    print("--- Generating Luau Registries ---")
    
    mat_type_def = """export type MaterialRegistryDefinition = { Id: string, Name: string, Density: number, Conductivity: number, Value: number }"""
    generate_luau_registry(materials, "src/Shared/Config/GeneratedMaterialRegistry.luau", "MaterialRegistry", mat_type_def)

    rxn_type_def = """export type ReactionRegistryDefinition = { Id: string, Name: string, RequiredMaterials: {[string]: number}, Catalyst: string?, MinTemperature: number, MaxTemperature: number, MinPressure: number, Product: string, YieldRatio: number, EnergyRequired: number, EntropyGenerated: number, DiscoveryRequirement: string? }"""
    generate_luau_registry(reactions, "src/Shared/Config/GeneratedReactionRegistry.luau", "ReactionRegistry", rxn_type_def)
    
    mach_type_def = """export type MachineRegistryDefinition = { Id: string, Name: string, PowerConsumption: number, MaxTemperature: number }"""
    generate_luau_registry(machines, "src/Shared/Config/GeneratedMachineRegistry.luau", "MachineRegistry", mach_type_def)

    res_type_def = """export type ResearchRegistryDefinition = { Id: string, Name: string, RequiredDiscoveries: {string}, Cost: number }"""
    generate_luau_registry(research, "src/Shared/Config/GeneratedResearchRegistry.luau", "ResearchRegistry", res_type_def)

    biome_type_def = """export type BiomeRegistryDefinition = { Id: string, Name: string, Temperature: number }"""
    generate_luau_registry(biomes, "src/Shared/Config/GeneratedBiomeRegistry.luau", "BiomeRegistry", biome_type_def)

    creature_type_def = """export type CreatureRegistryDefinition = { Id: string, Name: string, Health: number }"""
    generate_luau_registry(creatures, "src/Shared/Config/GeneratedCreatureRegistry.luau", "CreatureRegistry", creature_type_def)

    spirit_type_def = """export type SpiritRegistryDefinition = { Id: string, Name: string, Description: string, Rarity: string, Element: string, DropRate: string }"""
    generate_luau_registry(spirits, "src/Shared/Config/GeneratedSpiritRegistry.luau", "SpiritRegistry", spirit_type_def)

    badge_type_def = """export type BadgeRegistryDefinition = { Id: string, Name: string, Description: string, RarityPercent: number }"""
    generate_luau_registry(badges, "src/Shared/Config/GeneratedBadgeRegistry.luau", "BadgeRegistry", badge_type_def)

    recipe_type_def = """export type RecipeRegistryDefinition = { Id: string, Name: string, Description: string, Ingredients: {string}, OutputType: string }"""
    generate_luau_registry(recipes, "src/Shared/Config/GeneratedRecipeRegistry.luau", "RecipeRegistry", recipe_type_def)

    market_type_def = """export type MarketRegistryDefinition = { Id: string, Name: string, Description: string, Price: number, Currency: string, Category: string, ImageUrl: string }"""
    generate_luau_registry(market, "src/Shared/Config/GeneratedMarketRegistry.luau", "MarketRegistry", market_type_def)

    print("--- Exporting Modular JSON Registries ---")

    export_json([m.model_dump() for m in materials], f"{registry_dir}/materials.json")
    export_json([r.model_dump() for r in reactions], f"{registry_dir}/reactions.json")
    export_json([m.model_dump() for m in machines], f"{registry_dir}/machines.json")
    export_json([r.model_dump() for r in research], f"{registry_dir}/research.json")
    export_json([b.model_dump() for b in biomes], f"{registry_dir}/biomes.json")
    export_json([c.model_dump() for c in creatures], f"{registry_dir}/creatures.json")
    export_json([s.model_dump() for s in spirits], f"{registry_dir}/spirits.json")
    export_json([b.model_dump() for b in badges], f"{registry_dir}/badges.json")
    export_json([r.model_dump() for r in recipes], f"{registry_dir}/recipes.json")
    export_json([m.model_dump() for m in market], f"{registry_dir}/market.json")

    # Generate Bundle
    bundle_data = {
        "materials": "materials.json",
        "reactions": "reactions.json",
        "machines": "machines.json",
        "research": "research.json",
        "biomes": "biomes.json",
        "creatures": "creatures.json",
        "spirits": "spirits.json",
        "badges": "badges.json",
        "recipes": "recipes.json",
        "market": "market.json"
    }
    export_json(bundle_data, f"{registry_dir}/bundle.json")

    # Generate Manifest
    raw_content = json.dumps(bundle_data, sort_keys=True)
    # Combine hashes of all files
    content_hash = hashlib.sha256()
    for filename in bundle_data.values():
        path = f"{registry_dir}/{filename}"
        if os.path.exists(path):
            with open(path, "rb") as f:
                content_hash.update(f.read())
    
    manifest = {
        "version": "1.0.0",
        "generated_at": datetime.datetime.now(datetime.UTC).isoformat() + "Z",
        "git_commit": get_git_commit(),
        "content_hash": content_hash.hexdigest(),
        "schema_version": "v11",
        "pipeline_version": "1.0",
        "entity_counts": {
            "materials": len(materials),
            "reactions": len(reactions),
            "machines": len(machines),
            "research": len(research),
            "biomes": len(biomes),
            "creatures": len(creatures),
            "spirits": len(spirits),
            "badges": len(badges),
            "recipes": len(recipes),
            "market": len(market),
        }
    }
    export_json(manifest, f"{registry_dir}/manifest.json")
    
    print(f"🌐 Content Pipeline Completed. Content Hash: {manifest['content_hash']}")

if __name__ == "__main__":
    main()
